//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_EOS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLog
    {
        public int CallLogID { get; set; }
        public int EmployeeID { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime CallDateTime { get; set; }
        public string CallType { get; set; }
        public string Notes { get; set; }
    }
}
