//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_EOS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
