//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_EOS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Image { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> CategoriesID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
    }
}
